src/main/java/com/easycerti/eframe/common/vo/SearchBase.java
package com.easycerti.eframe.common.vo;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;

import com.easycerti.eframe.common.util.DateUtil;
import com.easycerti.eframe.common.util.PageInfo;

/**
 * 
 * 설명
 * 대부분의 검색조건에 search_from 과 search_to 필드가
 * 검색조건으로 들어가는 곳에 사용하자
 * 
 * @author hwkim
 * @since 2015. 6. 12.
 * @version 1.0
 * @see
 *
 *      <pre>
 * << 개정이력(Modification Information) >>
 *  
 *   수정일            수정자           수정내용
 *  --------------    -------------    ----------------------
 *   2015. 6. 12.           easy            최초 생성
 *
 * </pre>
 */
public class SearchBase extends PageInfo {
	
	private final static short DEFAULT_TERM = 7;
	
	// fields
	private String search_from;
	private String search_to;
	
	private String main_menu_id;
	private String sub_menu_id;
	
	// constructors
	public SearchBase() {super();}
	public SearchBase(int page_num, int page_size) {
		super(page_num, page_size);
	}
	
	/**
	 * 오늘부터 7일전으로 날짜 세팅
	 * 
	 * @author hwkim
	 * @since 2015. 6. 12.
	 * @return void
	 */
	public void initDatesWithDefaultIfEmpty() {
		initDatesWithDefaultIfEmpty(DEFAULT_TERM);
	}
	
	/**
	 * 오늘 부터 일정기간 전으로 날짜 세팅
	 * 
	 * @author hwkim
	 * @since 2015. 6. 12.
	 * @return void
	 */
	public void initDatesWithDefaultIfEmpty(int term) {
		if ("".equals(getSearch_from()) || "".equals(getSearch_to())) {
			search_to = DateUtil.getDateToString();
			try {
				search_from = DateUtil.addDate(search_to, -term);
			} catch (ParseException e) {
				throw new ESException("SYS101J");
			}
		}
	}
	
	public void initDatesWithTerm(int term) {
		if ("".equals(getSearch_from()) || "".equals(getSearch_to())) {
			String today = DateUtil.getDateToString();
			try {
				search_from = DateUtil.addDate(today, -term);
				search_to = search_from;
			} catch (ParseException e) {
				throw new ESException("SYS101J");
			}
		}
	}
	
	public void initDatesWithDefaultIfEmptyByMonth(int term) {
		if ("".equals(getSearch_from()) || "".equals(getSearch_to())) {
			search_to = DateUtil.getDateToString();
			try {
				search_from = DateUtil.addMonth(search_to, -term);
			} catch (ParseException e) {
				throw new ESException("SYS101J");
			}
		}
	}
	
	public void initDateByMonth(String year, String month) {
		try {
			Calendar cal = new GregorianCalendar(Locale.KOREA);
			SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
			cal.set(Integer.parseInt(year), Integer.parseInt(month)-1, 1);
			search_from = sdf.format(cal.getTime());
			cal.setTime(sdf.parse(search_from));
			int day = cal.getActualMaximum(Calendar.DAY_OF_MONTH);
			cal.set(Integer.parseInt(year), Integer.parseInt(month)-1, day);
			search_to = sdf.format(cal.getTime());
		} catch (ParseException e) {
			throw new ESException("SYS101J");
		}
	}
	
	/**
	 * 
	 * 특정한 시작 날짜와 종료날짜로 설정
	 * 
	 * @author easy
	 * @since 2015. 6. 12.
	 * @return void
	 */
	public void initDatesIfEmpty(Date search_from, Date search_to) {
		if ("".equals(getSearch_from()) || "".equals(getSearch_to())) {
			
			this.search_from = DateUtil.getDateToString(search_from, "yyyyMMdd");
			this.search_to = DateUtil.getDateToString(search_to, "yyyyMMdd");
		}
	}
	
	public void initDatesIfEmpty_2week(Date search_from, Date search_to) {
		if ("".equals(getSearch_from()) || "".equals(getSearch_to())) {
			
			Calendar cal = new GregorianCalendar(Locale.KOREA);
			cal.setTime(search_from);
			cal.add(Calendar.DAY_OF_YEAR, -14); // 하루를 더한다. 
			
			this.search_from = DateUtil.getDateToString(cal.getTime(), "yyyyMMdd");
			this.search_to = DateUtil.getDateToString(search_to, "yyyyMMdd");
		}
	}
	
	public void initDatesIfEmpty_week(Date search_from, Date search_to) {
		if ("".equals(getSearch_from()) || "".equals(getSearch_to())) {
			
			Calendar cal = new GregorianCalendar(Locale.KOREA);
			cal.setTime(search_from);
			cal.add(Calendar.DAY_OF_YEAR, -7); 
			
			this.search_from = DateUtil.getDateToString(cal.getTime(), "yyyyMMdd");
			this.search_to = DateUtil.getDateToString(search_to, "yyyyMMdd");
		}
	}
	
	public void initDatesIfEmpty_week(Date search_from, Date search_to, int amount) {
		if ("".equals(getSearch_from()) || "".equals(getSearch_to())) {
			
			Calendar cal = new GregorianCalendar(Locale.KOREA);
			cal.setTime(search_from);
			cal.add(Calendar.DATE, -7 * amount); 
			
			this.search_from = DateUtil.getDateToString(cal.getTime(), "yyyyMMdd");
			this.search_to = DateUtil.getDateToString(search_to, "yyyyMMdd");
		}
	}
	
	public void initDatesIfEmpty_month(Date search_from, Date search_to, int amount) {
		if ("".equals(getSearch_from()) || "".equals(getSearch_to())) {
			
			Calendar cal = new GregorianCalendar(Locale.KOREA);
			cal.setTime(search_from);
			cal.add(Calendar.MONTH, -amount);
			
			this.search_from = DateUtil.getDateToString(cal.getTime(), "yyyyMMdd");
			this.search_to = DateUtil.getDateToString(search_to, "yyyyMMdd");
		}
	}
	
	// getters and setters
	public String getSearch_from() {
		return (search_from == null?"":search_from);
	}
	public String getMain_menu_id() {
		return main_menu_id;
	}
	public void setMain_menu_id(String main_menu_id) {
		this.main_menu_id = main_menu_id;
	}
	public String getSub_menu_id() {
		return sub_menu_id;
	}
	public void setSub_menu_id(String sub_menu_id) {
		this.sub_menu_id = sub_menu_id;
	}
	public void setSearch_from(String search_from) {
		this.search_from = search_from.replaceAll("-", "");
	}
	public String getSearch_to() {
		return (search_to == null?"":search_to);
	}
	public void setSearch_to(String search_to) {
		this.search_to = search_to.replaceAll("-", "");
	}
	public String getSearch_fromWithHyphen() {
		return (search_from == null?"":DateUtil.getStringWithHyphen(search_from));
	}
	public String getSearch_toWithHyphen() {
		return (search_to == null?"":DateUtil.getStringWithHyphen(search_to));
	}

	// toString
	@Override
	public String toString() {
		return "SearchBase [search_from=" + search_from + ", search_to=" + "]";
	}
}

src/main/java/com/easycerti/eframe/psm/calling_management/vo/CallingApproval.java
package com.easycerti.eframe.psm.calling_management.vo;

import java.io.Serializable;
import java.sql.Timestamp;

import com.easycerti.eframe.core.type.YesNo;
import com.easycerti.eframe.psm.calling_management.type.Judge;

public class CallingApproval implements Serializable {

	private static final long serialVersionUID = 2738413073053062419L;

	// fields
	private int cll_dmnd_id;
	private short repeat_cnt;
	private short approval_seq;
	private String approver_id;
	private String approver_name;
	private String approver_dept_id;
	private String approver_dept_name;
	private YesNo is_approved;
	private Judge judge_result;
	private String judge;
	private String inserter_id;
	private Timestamp inserted_date;
	private String updater_id;
	private Timestamp updated_date;
	
	// methods
	public boolean isApprover(String user_id) {
		if (approver_id.equals(user_id))
			return true;
		return false;
	}
	
	// getters and setters
	public int getCll_dmnd_id() {
		return cll_dmnd_id;
	}
	public void setCll_dmnd_id(int cll_dmnd_id) {
		this.cll_dmnd_id = cll_dmnd_id;
	}
	public short getRepeat_cnt() {
		return repeat_cnt;
	}
	public void setRepeat_cnt(short repeat_cnt) {
		this.repeat_cnt = repeat_cnt;
	}
	public short getApproval_seq() {
		return approval_seq;
	}
	public void setApproval_seq(short approval_seq) {
		this.approval_seq = approval_seq;
	}
	public String getApprover_id() {
		return approver_id;
	}
	public void setApprover_id(String approver_id) {
		this.approver_id = approver_id;
	}
	public String getApprover_name() {
		return approver_name;
	}
	public void setApprover_name(String approver_name) {
		this.approver_name = approver_name;
	}
	public String getApprover_dept_id() {
		return approver_dept_id;
	}
	public void setApprover_dept_id(String approver_dept_id) {
		this.approver_dept_id = approver_dept_id;
	}
	public String getApprover_dept_name() {
		return approver_dept_name;
	}
	public void setApprover_dept_name(String approver_dept_name) {
		this.approver_dept_name = approver_dept_name;
	}
	public YesNo getIs_approved() {
		return (is_approved == null?YesNo.NO:is_approved);
	}
	public void setIs_approved(YesNo is_approved) {
		this.is_approved = is_approved;
	}
	public Judge getJudge_result() {
		return judge_result;
	}
	public void setJudge_result(Judge judge_result) {
		this.judge_result = judge_result;
	}
	public String getJudge() {
		return judge;
	}
	public void setJudge(String judge) {
		this.judge = judge;
	}
	public String getInserter_id() {
		return inserter_id;
	}
	public void setInserter_id(String inserter_id) {
		this.inserter_id = inserter_id;
	}
	public Timestamp getInserted_date() {
		return inserted_date;
	}
	public void setInserted_date(Timestamp inserted_date) {
		this.inserted_date = inserted_date;
	}
	public String getUpdater_id() {
		return updater_id;
	}
	public void setUpdater_id(String updater_id) {
		this.updater_id = updater_id;
	}
	public Timestamp getUpdated_date() {
		return updated_date;
	}
	public void setUpdated_date(Timestamp updated_date) {
		this.updated_date = updated_date;
	}

	// toString
	@Override
	public String toString() {
		return "CallingApproval [cll_dmnd_id=" + cll_dmnd_id + ", repeat_cnt="
				+ repeat_cnt + ", approval_seq=" + approval_seq
				+ ", approver_id=" + approver_id + ", approver_name="
				+ approver_name + ", approver_dept_id=" + approver_dept_id
				+ ", approver_dept_name=" + approver_dept_name
				+ ", is_approved=" + is_approved + ", judge_result="
				+ judge_result + ", judge=" + judge + ", inserter_id="
				+ inserter_id + ", inserted_date=" + inserted_date
				+ ", updater_id=" + updater_id + ", updated_date="
				+ updated_date + "]";
	}
}

src/main/java/com/easycerti/eframe/psm/calling_management/vo/CallingBizLog.java
package com.easycerti.eframe.psm.calling_management.vo;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;

public class CallingBizLog implements Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 8196104843383884741L;

	// fields
	private long log_seq;
	private String proc_date;
	private String proc_time;
	private String user_ip;
	private String scrn_id;
	private String scrn_name;
	private String req_type;
	private String system_seq;
	private String server_seq;
	private String req_context;
	private String req_url;
	private String req_end_time;
	private String inserter_id;
	private Timestamp inserted_date;
	
	private List<CallingBizLogResult> bizLogResultList;
	
	// getters and setters
	public long getLog_seq() {
		return log_seq;
	}
	public void setLog_seq(long log_seq) {
		this.log_seq = log_seq;
	}
	public String getProc_date() {
		return proc_date;
	}
	public void setProc_date(String proc_date) {
		this.proc_date = proc_date;
	}
	public String getProc_time() {
		return proc_time;
	}
	public void setProc_time(String proc_time) {
		this.proc_time = proc_time;
	}
	public String getUser_ip() {
		return user_ip;
	}
	public void setUser_ip(String user_ip) {
		this.user_ip = user_ip;
	}
	public String getScrn_id() {
		return scrn_id;
	}
	public void setScrn_id(String scrn_id) {
		this.scrn_id = scrn_id;
	}
	public String getScrn_name() {
		return scrn_name;
	}
	public void setScrn_name(String scrn_name) {
		this.scrn_name = scrn_name;
	}
	public String getReq_type() {
		return req_type;
	}
	public void setReq_type(String req_type) {
		this.req_type = req_type;
	}
	public String getSystem_seq() {
		return system_seq;
	}
	public void setSystem_seq(String system_seq) {
		this.system_seq = system_seq;
	}
	public String getServer_seq() {
		return server_seq;
	}
	public void setServer_seq(String server_seq) {
		this.server_seq = server_seq;
	}
	public String getReq_context() {
		return req_context;
	}
	public void setReq_context(String req_context) {
		this.req_context = req_context;
	}
	public String getReq_url() {
		return req_url;
	}
	public void setReq_url(String req_url) {
		this.req_url = req_url;
	}
	public String getReq_end_time() {
		return req_end_time;
	}
	public void setReq_end_time(String req_end_time) {
		this.req_end_time = req_end_time;
	}
	public String getInserter_id() {
		return inserter_id;
	}
	public void setInserter_id(String inserter_id) {
		this.inserter_id = inserter_id;
	}
	public Timestamp getInserted_date() {
		return inserted_date;
	}
	public void setInserted_date(Timestamp inserted_date) {
		this.inserted_date = inserted_date;
	}
	
	public List<CallingBizLogResult> getBizLogResultList() {
		return bizLogResultList;
	}
	public void setBizLogResultList(List<CallingBizLogResult> bizLogResultList) {
		this.bizLogResultList = bizLogResultList;
	}
	
	// toString
	@Override
	public String toString() {
		return "CallingBizLog [log_seq=" + log_seq + ", proc_date=" + proc_date
				+ ", proc_time=" + proc_time + ", user_ip=" + user_ip
				+ ", scrn_id=" + scrn_id + ", scrn_name=" + scrn_name
				+ ", req_type=" + req_type + ", system_seq=" + system_seq
				+ ", server_seq=" + server_seq + ", req_context=" + req_context
				+ ", req_url=" + req_url + ", req_end_time=" + req_end_time
				+ ", inserter_id=" + inserter_id + ", inserted_date="
				+ inserted_date + ", bizLogResultList=" + bizLogResultList
				+ "]";
	}
}

src/main/java/com/easycerti/eframe/psm/calling_management/vo/CallingBizLogResult.java
package com.easycerti.eframe.psm.calling_management.vo;

import java.io.Serializable;
import java.sql.Timestamp;

public class CallingBizLogResult implements Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 4321728618510399484L;
	
	// fields
	private long biz_log_result_seq;
	private long log_seq;
	private String result_type;
	private String result_content;
	private Timestamp inserted_date;
	
	// getters and setters
	public long getBiz_log_result_seq() {
		return biz_log_result_seq;
	}
	public void setBiz_log_result_seq(long biz_log_result_seq) {
		this.biz_log_result_seq = biz_log_result_seq;
	}
	public long getLog_seq() {
		return log_seq;
	}
	public void setLog_seq(long log_seq) {
		this.log_seq = log_seq;
	}
	public String getResult_type() {
		return result_type;
	}
	public void setResult_type(String result_type) {
		this.result_type = result_type;
	}
	public String getResult_content() {
		return result_content;
	}
	public void setResult_content(String result_content) {
		this.result_content = result_content;
	}
	public Timestamp getInserted_date() {
		return inserted_date;
	}
	public void setInserted_date(Timestamp inserted_date) {
		this.inserted_date = inserted_date;
	}
	
	// toString
	@Override
	public String toString() {
		return "CallingBizLogResult [biz_log_result_seq=" + biz_log_result_seq
				+ ", log_seq=" + log_seq + ", result_type=" + result_type
				+ ", result_content=" + result_content + ", inserted_date="
				+ inserted_date + "]";
	}
}

src/main/java/com/easycerti/eframe/psm/calling_management/vo/CallingDemandReason.java
package com.easycerti.eframe.psm.calling_management.vo;

import java.io.Serializable;
import java.sql.Timestamp;

public class CallingDemandReason implements Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -7985164314415616822L;
	
	// fields
	private int cll_dmnd_id;
	private short repeat_cnt;
	private String reason;
	private String inserter_id;
	private String inserter_name;
	private String inserter_dept_id;
	private String inserter_dept_name;
	private Timestamp inserted_date;
	private String updater_id;
	private Timestamp updated_date;
	
	// constructors
	public CallingDemandReason() {}
	public CallingDemandReason(int cll_dmnd_id, short repeat_cnt, String reason) {
		this.cll_dmnd_id = cll_dmnd_id;
		this.repeat_cnt = repeat_cnt;
		this.reason = reason;
	}
	
	// getters and setters
	public int getCll_dmnd_id() {
		return cll_dmnd_id;
	}
	public void setCll_dmnd_id(int cll_dmnd_id) {
		this.cll_dmnd_id = cll_dmnd_id;
	}
	public short getRepeat_cnt() {
		return repeat_cnt;
	}
	public void setRepeat_cnt(short repeat_cnt) {
		this.repeat_cnt = repeat_cnt;
	}
	public String getReason() {
		return reason;
	}
	public void setReason(String reason) {
		this.reason = reason;
	}
	public String getInserter_id() {
		return inserter_id;
	}
	public void setInserter_id(String inserter_id) {
		this.inserter_id = inserter_id;
	}
	public String getInserter_name() {
		return inserter_name;
	}
	public void setInserter_name(String inserter_name) {
		this.inserter_name = inserter_name;
	}
	public String getInserter_dept_id() {
		return inserter_dept_id;
	}
	public void setInserter_dept_id(String inserter_dept_id) {
		this.inserter_dept_id = inserter_dept_id;
	}
	public String getInserter_dept_name() {
		return inserter_dept_name;
	}
	public void setInserter_dept_name(String inserter_dept_name) {
		this.inserter_dept_name = inserter_dept_name;
	}
	public Timestamp getInserted_date() {
		return inserted_date;
	}
	public void setInserted_date(Timestamp inserted_date) {
		this.inserted_date = inserted_date;
	}
	public String getUpdater_id() {
		return updater_id;
	}
	public void setUpdater_id(String updater_id) {
		this.updater_id = updater_id;
	}
	public Timestamp getUpdated_date() {
		return updated_date;
	}
	public void setUpdated_date(Timestamp updated_date) {
		this.updated_date = updated_date;
	}
	
	// toString
	@Override
	public String toString() {
		return "CallingDemandReason [cll_dmnd_id=" + cll_dmnd_id
				+ ", repeat_cnt=" + repeat_cnt + ", reason=" + reason
				+ ", inserter_id=" + inserter_id + ", inserter_name="
				+ inserter_name + ", inserter_dept_id=" + inserter_dept_id
				+ ", inserter_dept_name=" + inserter_dept_name
				+ ", inserted_date=" + inserted_date + ", updater_id="
				+ updater_id + ", updated_date=" + updated_date + "]";
	}
}

src/main/webapp/WEB-INF/views/psm/search/messageView.jsp
${message}

src/main/webapp/WEB-INF/views/psm/search/summonDelegation.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<%@taglib uri="/WEB-INF/tags2/tld2/ctl.tld" prefix="ctl"%>
<c:set var="currentMenuId" value="${index_id}" />
<ctl:checkMenuAuth menuId="${currentMenuId}" />
<ctl:drawNavMenu menuId="${currentMenuId}" />


<script
	src="${rootPath}/resources/js/psm/search/summonDelegation.js"
	type="text/javascript" charset="UTF-8"></script>
  <%-- <script
	src="${rootPath}/resources/assets/pages/scripts/table-datatables-ajax.min.js"
	type="text/javascript"></script>   --%>
	<script	src="${rootPath}/resources/assets/pages/scripts/table-datatables-ajax.min.js" type="text/javascript"></script>

<style type="text/css">
	.input_date {
		background-color: #eef1f5;
		padding: 0.3em 0.5em;
		border: 1px solid #e4e4e4;
		height: 30px;
		font-size: 12px;
		color: #555;
	}
	.fade.in {
	    opacity: 0;
	}
</style>

<h1 class="page-title">${currentMenuName}</h1>
<div class="portlet light portlet-fit portlet-datatable bordered">
	<div class="portlet-body">
		<div class="table-container">

			<div id="datatable_ajax_2_wrapper"
				class="dataTables_wrapper dataTables_extended_wrapper dataTables_extended_wrapper no-footer DTS">

				<div class="dataTables_scroll" style="position: relative;">
					<!-- 개인정보 예외 정책 등록 -->
					<div class="caption"  style="padding-bottom: 5px;">
						<i class="icon-settings font-dark"></i> <span
							class="caption-subject font-dark sbold uppercase">소명 판정자 위임</span>
					</div>
					 <form id="misForm" method="POST" class="mt-repeater form-horizontal">
					<div>
						<table style="border-top: 1px solid #e7ecf1"
							class="table table-bordered" id="datatable_ajax_2"
							aria-describedby="datatable_ajax_2_info" role="grid"
							style="position: absolute; top: 0px; left: 0px; width: 100%;">
							<thead>
								<th width="25%"
									style="border-bottom: 1px solid #e7ecf1; text-align: center;">
									판정자</th>
								<th width="25%"
									style="border-bottom: 1px solid #e7ecf1; text-align: center;">
									위임자</th>
								<th width="35%"
									style="border-bottom: 1px solid #e7ecf1; text-align: center;">
									위임기간</th>
								<th width="15%"
									style="border-bottom: 1px solid #e7ecf1; text-align: center;">
									추가</th>
							</thead>
							<tbody>
								<tr>
									<td align="center"><input type="text" name="admin_user"
										id="admin_user" class="form-control input-medium" value=${userSession.admin_user_name} readonly></td>
									<td align="center">
										<select class="form-control input-medium" name="emp_user" id="emp_user">
											<option value=""> -------- 선 택 -------- </option>
											<c:forEach items="${extrtCondbyInqList.extrtCondbyInq}" var="extrtCondbyInq" varStatus="status">
												<option value="${extrtCondbyInq.emp_user_id}"
													<c:if test="${extrtCondbyInq.emp_user_id == search.emp_user_id }">selected="selected"</c:if>>${extrtCondbyInq.emp_user_name}
												</option>
											</c:forEach>
										</select>
									</td>
									<td align="center">
										<div class="input-group input-medium date-picker input-daterange"
											data-date="10/11/2012" data-date-format="yyyy-mm-dd">
											<input type="text" class="form-control" id="search_from" 
												name="search_from" value="${search.search_fromWithHyphen}"> 
												<span class="input-group-addon"> &sim; </span> 
											<input type="text" class="form-control" id="search_to" 
												name="search_to" value="${search.search_toWithHyphen}">
										</div> 
									</td>
									<td align="center">
										<button type="button"
											class="btn btn-sm blue btn-outline sbold uppercase"
											onclick="javascript:summonUserAdd()">
											<i class="fa fa-plus"></i> 위임
										</button>
									</td>
								</tr>
							</tbody>
						</table>
						<input type="hidden" name="dept_id" id="dept_id" value="${search.dept_id}" />
						<input type="hidden" name="auth_ids" id="auth_ids" value="${search.auth_ids}"/>	
					</div>
					</form>
					
					<div class="caption" style="padding-bottom: 5px;">
						<i class="icon-settings font-dark"></i> <span
							class="caption-subject font-dark sbold uppercase"> 소명 판정자 위임 현황</span>
					</div>
						<div>
							<table style="border-top: 1px solid #e7ecf1"
								class="table table-striped table-bordered table-hover table-checkable dataTable no-footer"
								id="datatable_ajax_2" aria-describedby="datatable_ajax_2_info"
								role="grid"
								style="position: absolute; top: 0px; left: 0px; width: 100%;">
								<thead>
									<tr role="row" class="heading"
										style="background-color: #c0bebe;">
										<th width="25%"
											style="border-bottom: 1px solid #e7ecf1; text-align: center;">
											판정자</th>
										<th width="25%"
											style="border-bottom: 1px solid #e7ecf1; text-align: center;">
											위임자</th>
										<th width="35%"
											style="border-bottom: 1px solid #e7ecf1; text-align: center;">
											위임기간</th>
										<th width="15%"
											style="border-bottom: 1px solid #e7ecf1; text-align: center;">
											취소</th>
									</tr>
								</thead>
								<tbody>
								<c:choose>
									<c:when test="${empty delegationList.delegation}">
										<tr>
											<td colspan="4" align="center">데이터가 없습니다.</td>
										</tr>
									</c:when>
									<c:otherwise>
										<c:forEach items="${delegationList.delegation}" var="delegation" varStatus="status">
											<tr>
												<td style="border-bottom: 1px solid #e7ecf1; text-align: center;">${delegation.approval_name }</td>
												<td style="border-bottom: 1px solid #e7ecf1; text-align: center;">${delegation.delegation_name }</td>
												<td style="border-bottom: 1px solid #e7ecf1; text-align: center;">${delegation.delegation_date }</td>
												<td style="text-align: center">
													<c:choose>
														<c:when test="${delegation.cancel_yn == 'N' }">
															<p class="btn btn-xs red btn-outline filter-cancel"
																onclick="javascript:summonUserRemove('${delegation.delegation_seq }', '${delegation.delegation_id }')">취소</p>	
														</c:when>
														<c:otherwise>
															취소완료
														</c:otherwise>
													</c:choose>
												</td>
											</tr>
										</c:forEach>
									</c:otherwise>
								</c:choose>
								</tbody>
							</table>
						</div>
					<div class="dataTables_processing DTS_Loading"
						style="display: none;">Please wait ...</div>
				</div>
				<div class="row" style="padding: 10px;">
					<!-- 페이징 영역 -->
					<c:if test="${delegationList.page_total_count > 0}">
						<div align="center" id="pagingframe">
							<p>
								<ctl:paginator currentPage="${paramBean.page_cur_num}"
									rowBlockCount="${paramBean.page_size}"
									totalRowCount="${delegationList.page_total_count}" />
							</p>
						</div>
					</c:if>
				</div>
			</div>

		</div>
	</div>
</div>

<script type="text/javascript">
	var summonDelegation = {
		"listUrl" : "${rootPath}/extrtCondbyInq/summmonDelegation.html"
	};
</script>